[project]
name = "xiaoxiang"
version = "0.1.0"
description = ""
authors = [{ name = "Jacek Chmielewski", email = "jchmielewski@teonite.com" }]
readme = "README.md"

requires-python = ">=3.13,<3.14"

dependencies = [
     "bleak>=1.1,<1.2",
]
