[tool.poetry]
name = "xiaoxiang"
version = "0.1.0"
description = ""
authors = ["Jacek Chmielewski <jchmielewski@teonite.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
bleak = "^0.21.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
